"""Driver: run this repo's C++ reference build (build/ibpm) on the exact
same SD7003/SD8000 polar sweep + grid convergence cases as
run_all_airfoils.py/rerun_fine.py (same geometry files, same alphas, same
grid levels, same dt/nsteps -- including the dt=0.005 fix for the finest
convergence level, applied here from the start rather than as a follow-up
rerun). This lets the C++ implementation be added to the SD7003/SD8000
comparison figures alongside py/ibpm.py and the UIUC LSAT experimental data.

Requires build/ibpm (see build/Makefile); reuses the geometry files
SURF_test/geom/*.geom already generated by run_all_airfoils.py's
make_raw_for_dx (same raw boundary points -> same body for both
implementations).

Usage: python3 SURF_test/run_all_airfoils_cpp.py
Output: SURF_test/{SD7003,SD8000}/_run_data_cpp/, SURF_test/batch_results_cpp.json
"""
import json
import pathlib
import subprocess
import sys
import time

REPO = pathlib.Path("/Users/elina/Desktop/SURF2026/ibpm_py-main")
GEOMDIR = REPO / "SURF_test" / "geom"
CPP_BIN = REPO / "build" / "ibpm"

DOMAIN = dict(length=6, xoffset=-2, yoffset=-1.5)
AVG_FRAC = 0.6  # average over the last 60% of the run, matching airfoil_driver.time_avg_force

CASES = {
    "SD7003": dict(Re=61100, polar_alphas=[-2.92, -0.09, 1.66, 4.60, 7.72], conv_alpha=-0.09),
    "SD8000": dict(Re=60800, polar_alphas=[-3.88, -0.81, 2.29, 5.36, 8.36], conv_alpha=-0.81),
}

# same three grid levels as run_all_airfoils.py, but the finest level uses
# dt=0.005/nsteps=6000 from the start (py/ibpm.py's dx=0.01 polar-sweep dt
# of 0.01 diverged to NaN -- see SD7003/README.md's CFL note; C++ shares the
# same explicit convective term, so it needs the same fix)
CONV_LEVELS = [
    dict(tag="coarse", dx=0.04, nx=150, ny=75, dt=0.01, nsteps=3000),
    dict(tag="medium", dx=0.02, nx=300, ny=150, dt=0.01, nsteps=3000),
    dict(tag="fine", dx=0.01, nx=600, ny=300, dt=0.005, nsteps=6000),
]
POLAR_LEVEL = dict(dx=0.02, nx=300, ny=150, dt=0.01, nsteps=3000)


def geom_path_for_dx(name, dx):
    p = GEOMDIR / f"{name.lower()}_dx{dx:.4f}.geom"
    if not p.exists():
        raise FileNotFoundError(
            f"{p} missing -- run SURF_test/run_all_airfoils.py first "
            f"(it generates the resampled geometry files both implementations share)"
        )
    return p


def run_case_cpp(geom, name, outdir, alpha, nx, ny, length, xoffset, yoffset, dt, nsteps, Re,
                  restart=0, force_every=1):
    outdir = pathlib.Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    cmd = [str(CPP_BIN),
           "-geom", str(geom), "-name", name, "-outdir", str(outdir),
           "-nx", str(nx), "-ny", str(ny), "-ngrid", "1",
           "-length", str(length), "-xoffset", str(xoffset), "-yoffset", str(yoffset),
           "-alpha", str(alpha), "-Re", str(Re), "-dt", str(dt), "-nsteps", str(nsteps),
           "-tecplot", "0", "-restart", str(restart), "-force", str(force_every)]
    log_path = outdir / f"{name}_log.txt"
    t0 = time.time()
    with open(log_path, "w") as logf:
        proc = subprocess.run(cmd, cwd=REPO, stdout=logf, stderr=subprocess.STDOUT)
    elapsed = time.time() - t0
    if proc.returncode != 0:
        raise RuntimeError(f"C++ run failed ({name}): see {log_path}")
    return outdir / f"{name}.force", elapsed


def time_avg_force(force_path, frac=0.6):
    import numpy as np
    d = np.loadtxt(force_path)
    if d.ndim == 1:
        d = d[None, :]
    n = len(d)
    i0 = int(n * (1 - frac))
    seg = d[i0:]
    t = d[:, 1]
    cd_mean, cl_mean = seg[:, 2].mean(), seg[:, 3].mean()
    cd_std, cl_std = seg[:, 2].std(), seg[:, 3].std()
    return dict(cd_mean=float(cd_mean), cl_mean=float(cl_mean),
                cd_std=float(cd_std), cl_std=float(cl_std),
                t_final=float(t[-1]), n_steps=int(n))


def main():
    if not CPP_BIN.exists():
        print(f"ERROR: {CPP_BIN} not found. Build it first: cd build && make", file=sys.stderr)
        sys.exit(1)

    results = {"polar": {}, "convergence": {}}
    results_path = REPO / "SURF_test" / "batch_results_cpp.json"
    if results_path.exists():
        results = json.loads(results_path.read_text())

    for name, cfg in CASES.items():
        results.setdefault("polar", {}).setdefault(name, [])
        results.setdefault("convergence", {}).setdefault(name, [])
        done_alphas = {p["alpha"] for p in results["polar"][name]}
        done_tags = {c["tag"] for c in results["convergence"][name]}

        print(f"=== {name}: polar sweep (C++) at dx={POLAR_LEVEL['dx']} ===", flush=True)
        geom_path = geom_path_for_dx(name, POLAR_LEVEL["dx"])
        for alpha in cfg["polar_alphas"]:
            if alpha in done_alphas:
                print(f"  alpha={alpha:+.2f}: already done, skipping", flush=True)
                continue
            outdir = REPO / "SURF_test" / "high_re" / name / "_run_data_cpp" / f"polar_a{alpha:+.2f}"
            fpath, elapsed = run_case_cpp(
                geom=geom_path, name="run", outdir=outdir, alpha=alpha,
                nx=POLAR_LEVEL["nx"], ny=POLAR_LEVEL["ny"], Re=cfg["Re"],
                dt=POLAR_LEVEL["dt"], nsteps=POLAR_LEVEL["nsteps"], **DOMAIN,
            )
            stats = time_avg_force(fpath, frac=AVG_FRAC)
            stats.update(alpha=alpha, elapsed=elapsed, nx=POLAR_LEVEL["nx"], ny=POLAR_LEVEL["ny"])
            results["polar"][name].append(stats)
            print(f"  alpha={alpha:+.2f}  Cl={stats['cl_mean']:+.4f}±{stats['cl_std']:.4f}  "
                  f"Cd={stats['cd_mean']:+.4f}±{stats['cd_std']:.4f}  ({elapsed:.1f}s)", flush=True)
            results_path.write_text(json.dumps(results, indent=2))

        print(f"=== {name}: grid convergence (C++) at alpha={cfg['conv_alpha']} ===", flush=True)
        for lvl in CONV_LEVELS:
            if lvl["tag"] in done_tags:
                print(f"  {lvl['tag']}: already done, skipping", flush=True)
                continue
            geom_path = geom_path_for_dx(name, lvl["dx"])
            outdir = REPO / "SURF_test" / "high_re" / name / "_run_data_cpp" / f"conv_{lvl['tag']}"
            fpath, elapsed = run_case_cpp(
                geom=geom_path, name="run", outdir=outdir, alpha=cfg["conv_alpha"],
                nx=lvl["nx"], ny=lvl["ny"], Re=cfg["Re"],
                dt=lvl["dt"], nsteps=lvl["nsteps"], **DOMAIN,
            )
            stats = time_avg_force(fpath, frac=AVG_FRAC)
            stats.update(alpha=cfg["conv_alpha"], elapsed=elapsed, nx=lvl["nx"], ny=lvl["ny"],
                         dx=lvl["dx"], tag=lvl["tag"], dt=lvl["dt"])
            results["convergence"][name].append(stats)
            print(f"  {lvl['tag']:8s} dx={lvl['dx']:.3f} nx={lvl['nx']:4d}  "
                  f"Cl={stats['cl_mean']:+.4f}±{stats['cl_std']:.4f}  "
                  f"Cd={stats['cd_mean']:+.4f}±{stats['cd_std']:.4f}  ({elapsed:.1f}s)", flush=True)
            results_path.write_text(json.dumps(results, indent=2))

    print("ALL DONE", flush=True)


if __name__ == "__main__":
    main()
